In [63]:
import numpy as np
from scipy import sparse

# Create a 2D Numpy array with a diagonal of ones, and zeros everywhere eles with method eye
eye = np.eye(4)
print("Numpy array:\n{}".format(eye))


# Create a 2D Numpy array with a diagonal of ones, and zeros everywhere eles with method eye with k = number of shifting
# Shift k = 1 means that shift 1 column to the right 
eye1 = np.eye(4, k=1)
print("\nNumpy array + shift 1 column to the right:\n{}".format(eye1))

Numpy array:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Numpy array + shift 1 column to the right:
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [65]:
# Create a reverse identity matrix (also called anti-diagonal matrix)

# 1. Use method np.fliplr() to flip the identity matrix left-to-right
reverse_eye = np.fliplr(np.eye(4))
print(f"The reverse eye is:\n{reverse_eye}\n")


reverse_eye1 = np.fliplr(np.eye(4, k=1))
print(f"The reverse eye with shift k = 1 means that shift 1 column to the right is:\n{reverse_eye1}\n")


# Method 2. Use slicing place to place 1s manually
manually_replace_1 = np.zeros((3,3)) # This will create a 3x3 matrix of zeros
print(f"First: Create a 3x3 matrix of zeros\n{manually_replace_1}\n")

np.fill_diagonal(manually_replace_1, 1)
print("Then mannually fill diagonal with 1:")
print(f"{manually_replace_1}\n")


print("Lastly, Flip left-to-right")
print(np.fliplr(manually_replace_1))


The reverse eye is:
[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]

The reverse eye with shift k = 1 means that shift 1 column to the right is:
[[0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 0.]]

First: Create a 3x3 matrix of zeros
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Then mannually fill diagonal with 1:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Lastly, Flip left-to-right
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
