In [57]:
# NumPy --> ndarray (n-dimensional) --> 2D

import numpy as np

x = np.array([[1, 2, 3], [4, 5, 6]])
print(f"this is a 2D: {x.shape} means that there are 2 rows and 3 columns")
print("x:\n{}".format(x))

this is a 2D: (2, 3) means that there are 2 rows and 3 columns
x:
[[1 2 3]
 [4 5 6]]


In [59]:
# NumPy --> ndarray (n-dimensional) --> 2D

y = np.array([[1, 2, 3], [4, 5, 6,], [7, 8, 9]])
print(f"this is a 2D: {y.shape} means that there are 3 rows and 3 columns")
print("y:\n{}".format(y))

this is a 2D: (3, 3) means that there are 3 rows and 3 columns
y:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [61]:
# NumPy --> ndarray (n-dimensional) --> 3D
z = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print(f"this is a 3D: {z.shape} means that there are 2 blocks or 2 depth layers")
print("So, 2 blocks, each 2x2 matrix")
print(f"Block 1:\n[1, 2]\n[3, 4]")
print(f"Block 2:\n[5, 6]\n[7, 8]\n\n so,")
print("z:\n{}".format(z))

this is a 3D: (2, 2, 2) means that there are 2 blocks or 2 depth layers
So, 2 blocks, each 2x2 matrix
Block 1:
[1, 2]
[3, 4]
Block 2:
[5, 6]
[7, 8]

 so,
z:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [63]:
# NumPy --> ndarray (n-dimensional) --> 3D
w = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]],
    [[9, 0], [0, 1]],
])
print(f"this is a 3D: {w.shape} means that there are 3 blocks or 3 depth layers")
print("So, 3 blocks, each 2x2 matrix")
print(f"Block 1:\n[1, 2]\n[3, 4]")
print(f"Block 2:\n[5, 6]\n[7, 8]")
print(f"Block 3:\n[9, 0]\n[0, 1]\n\n so,")
print("z:\n{}".format(w))

this is a 3D: (3, 2, 2) means that there are 3 blocks or 3 depth layers
So, 3 blocks, each 2x2 matrix
Block 1:
[1, 2]
[3, 4]
Block 2:
[5, 6]
[7, 8]
Block 3:
[9, 0]
[0, 1]

 so,
z:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]

 [[9 0]
  [0 1]]]
